spring:
  redis:
    host: localhost
    port: 6379
redis:
  key:
    user: "oschajsa:user"
    store: "oschajsa:store"
    user-store: "oschajsa:user-store"
    prepare-close-store: "oschajsa:prepare-close-store"