file-upload:
  url: /Users/lee-jaeyong/Desktop/file-upload

jwt:
  secretkey: oschajsa
  expire: 600000

spring:
  h2:
    console:
      enabled: false
      settings:
        trace: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oschajsa?serverTimezone=UTC&characterEncoding=UTF-8
    password: root
    username: root

kakao:
  openAPI:
    path: /v2/local/geo/coord2address.json
    service-key: KakaoAK d40c82c42db0892f356fd71c6c36c7a0
    protocol: https
    host: dapi.kakao.com