version: "3"
services: 
 db: 
  image: mysql:5.7.35
  container_name: mysql
  ports:
  - "3306:3306"
  environment:
   TZ: Asia/Seoul
   MYSQL_ROOT_PASSWORD: "root"
   MYSQL_DATABASE: "oschajsa"
  command: # 명령어 실행
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_unicode_ci